# Generated by Django 4.0.5 on 2022-06-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood_app', '0005_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='neighborhood_admin',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
