# Generated by Django 4.0.5 on 2022-06-19 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood_app', '0006_admin_neighborhood_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='neighborhood_admin',
            new_name='neighborhood_administered',
        ),
    ]
