# Generated by Django 4.0.5 on 2022-06-19 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood_app', '0007_rename_neighborhood_admin_admin_neighborhood_administered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbors', to='neighbourhood_app.neighborhood'),
        ),
    ]
