# Generated by Django 4.0.5 on 2022-06-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood_app', '0013_remove_user_groups_remove_user_neighborhood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='businesspics/'),
        ),
    ]
