# Generated by Django 4.0.5 on 2022-06-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood_app', '0014_business_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='landmark',
            field=models.ImageField(blank=True, null=True, upload_to='landmarks/'),
        ),
    ]
