# Generated by Django 4.0.5 on 2022-06-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood_app', '0016_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post',
            field=models.TextField(blank=True, null=True),
        ),
    ]
