# Generated by Django 4.0.5 on 2022-06-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood_app', '0019_alter_neighborhood_admin_alter_neighborhood_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='occupants',
        ),
    ]
